site_name: Snowman

nav:
  - Home: index.md
  - Basic usage:
      - Getting Started: basic_usage/getting_started.md
      - Concepts and Terminology: basic_usage/concepts.md
      - Datasets: basic_usage/datasets.md
      - Matching solutions: basic_usage/matching_solutions.md
      - Experiments: basic_usage/experiments.md
      - Configuring Analyses: basic_usage/configuring_analyses.md
      - Workflows:
          - Comparing Matching Solutions: basic_usage/workflows/comparing_matching_solutions.md
          - Improving Matching Solutions: basic_usage/workflows/improving_matching_solutions.md
      - Analyses:
          - Overview: basic_usage/analyses/overview.md
          - Binary Metrics View: basic_usage/analyses/binary_metrics_view.md
          - KPI Decision Matrix: basic_usage/analyses/kpi_decision_matrix.md
          - KPI Investigator: basic_usage/analyses/kpi_investigator.md
          - N-Intersection Viewer: basic_usage/analyses/n_intersection_viewer.md
          - N-Metrics Table: basic_usage/analyses/n_metrics_table.md
          - Similarity Diagrams: basic_usage/analyses/similarity_diagrams.md
  - Advanced setups:
      - Remote Instances: advanced_setups/remote_instances.md
      - Connect your Code: advanced_setups/code_connection.md
  - Development:
      - Setup: dev_setup/introduction.md
      - Contributing: dev_setup/contrib-knowledge.md
      - REST API: ./openapi
  - SIGMOD2021: sigmod2021.md

extra_css:
  - assets/extra.css

repo_url: https://github.com/HPI-Information-Systems/snowman
repo_name: snowman (GitHub)

theme:
  name: material
  logo: assets/logo/V2-128.png
  favicon: assets/logo/V2-64.png

plugins:
  - search

markdown_extensions:
  - admonition
