site_name: Snowman

nav:
  - Home: index.md
  - Showcase: showcase/main.md
  - Basic usage:
      - Getting Started: basic_usage/getting_started.md
      - Concepts and Terminology: basic_usage/concepts.md
      - Datasets: basic_usage/datasets.md
      - Matching solutions: basic_usage/matching_solutions.md
      - Experiments: basic_usage/experiments.md
      - Configuring Analyses: basic_usage/configuring_analyses.md
      - Workflows:
          - Comparing matching solutions: basic_usage/workflow/comparing_matchingsolutions.md
          - Evaluating experiments: basic_usage/workflow/evaluate_experiments.md
  - Advanced setups:
      - Remote instances: advanced_setups/remote_instances.md
      - Connect your code: advanced_setups/code_connection.md
  - Development:
      - Setup: dev_setup/introduction.md
      - Contributing: dev_setup/contrib-knowledge.md
      - REST API: ./swagger
  - SIGMOD2021: sigmod2021.md

extra_css:
  - assets/extra.css

repo_url: https://github.com/HPI-Information-Systems/snowman
repo_name: snowman (GitHub)

theme:
  name: material
  logo: assets/V2-128.png
  favicon: assets/V2-64.png

plugins:
  - search

markdown_extensions:
  - admonition
